[package]
name = "toop"
version = "0.0.0"

[[bin]]
name = "toop"
path = "src/main/rust/mod.rs"
test = false
doctest = false
bench = false

[dependencies]
volatile = "0.4.5"
spin = "0.9.4"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
